### ISSUE TITLE
Decoding custom types

### ISSUE THREAD

**Issue by altonen** [polkascan/py-scale-codec#108]
Hello and thanks for writing this library. I'm working a project that requires decoding somewhat arbitrary SCALE-encoded data that contains types from Substrate. One such example is [`BlockAnnounce`](https://github.com/paritytech/substrate/blob/master/client/network/common/src/sync/message.rs#L190) which is generic over `Header`. I'm a little hazy on the details of `MetadataV14` so I don't know how to express `BlockAnnounce` as a type that `py-scale-codec` can decode. What I did was grabbed a SCALE-encoded byte vector representing a block announcement and since it's not part of the metadata that Substrate exposes, I expressed it as a custom type but I can't get it to decode fully. Here is what I tried:

```python
from scalecodec.base import RuntimeConfigurationObject, ScaleBytes, RuntimeConfiguration
from scalecodec.type_registry import load_type_registry_preset

RuntimeConfiguration().update_type_registry(load_type_registry_preset("core"))
RuntimeConfiguration().update_type_registry(load_type_registry_preset("legacy"))
metadata = open("metadata.scale").read()
metadata_decoder = RuntimeConfiguration().create_scale_object(
    'MetadataVersioned', data=ScaleBytes(metadata)
)
metadata_decoder.decode()
RuntimeConfiguration().add_portable_registry(metadata_decoder)

RuntimeConfiguration().update_type_registry({
    "types": {
        "BlockAnnounce": {
            "type": "struct",
            "type_mapping": [
                [
                    "header",
                    "Header",
                ],
                [
                    "state",
                    "Option<BlockState>",
                ],
                [
                    "data",
                    "Option<Vec<u8>>",
                ],
            ],
        },
        "BlockState": {
            "type": "enum",
            "type_mapping": [
                [
                    "Normal",
                    "Null",
                ],
                [
                    "Best",
                    "Null",
                ],
            ]
        },
    }
})

data = ScaleBytes("0xa643a4ac16c3f49d679e82afea2838f8f109c21e674bb8c6ed2b5d128e1b784da8bb41fd94f98cec33a552bde5882ebd8c1421a6233d3413bb7a3bf6fad5fb8548baf6d3dc3bd528632179de171427bf2c724cff551495e131fa35770338661757261208ba8af1000005617572611148d6e438a04c9160c260f0811f37546de75e69236f2dfb230bbd1bc79fec01255af932f8d488a5693e31518a22212dfc19d726d4f279eb22355422caff8510")
obj = RuntimeConfiguration().create_scale_object(
    'Vec<BlockAnnounce>',
    data,
    metadata = metadata_decoder,
)
obj.decode()
```
where `metadata.scale` contains the exported metadata received from a chain that I've saved a to file to help with testing and where `data` is a block announcement that Substrate is able to decode properly. This is the error I get when I try to run the program:

```
Traceback (most recent call last):
  File "/home/altonen/code/py-scale-testing/main.py", line 57, in <module>
    obj.decode()
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 880, in decode
    self.value_serialized = self.process()
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/types.py", line 971, in process
    element = self.process_type(self.sub_type, metadata=self.metadata)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 985, in process_type
    obj.decode(check_remaining=False)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 880, in decode
    self.value_serialized = self.process()
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/types.py", line 573, in process
    field_obj = self.process_type(data_type, metadata=self.metadata)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 985, in process_type
    obj.decode(check_remaining=False)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 880, in decode
    self.value_serialized = self.process()
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/types.py", line 573, in process
    field_obj = self.process_type(data_type, metadata=self.metadata)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 985, in process_type
    obj.decode(check_remaining=False)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 880, in decode
    self.value_serialized = self.process()
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/types.py", line 573, in process
    field_obj = self.process_type(data_type, metadata=self.metadata)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 985, in process_type
    obj.decode(check_remaining=False)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 880, in decode
    self.value_serialized = self.process()
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/types.py", line 971, in process
    element = self.process_type(self.sub_type, metadata=self.metadata)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 985, in process_type
    obj.decode(check_remaining=False)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 880, in decode
    self.value_serialized = self.process()
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/types.py", line 1240, in process
    result_obj = self.process_type(enum_type_mapping[1], metadata=self.metadata)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 985, in process_type
    obj.decode(check_remaining=False)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 880, in decode
    self.value_serialized = self.process()
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/types.py", line 573, in process
    field_obj = self.process_type(data_type, metadata=self.metadata)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 985, in process_type
    obj.decode(check_remaining=False)
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/base.py", line 895, in decode
    raise RemainingScaleBytesNotEmptyException(
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Decoding <HexBytes> - No more bytes available (needed: 4724 / total: 174)
```

I attempted to debug this and it's able to decode the block announcement all the way to `Compact<u32>` so it works to an extent and then it crashes, here's the log: 
```
<snip>
decoder class found 'Vec<BlockAnnounce>'
decoder class found 'Compact<u32>'
decoder class found 'BlockAnnounce'
decoder class found 'Header'
decoder class found 'Hash'
decoder class found 'Compact<BlockNumber>'
decoder class found 'Hash'
decoder class found 'Hash'
decoder class found 'sp_runtime::generic::digest::digest'
decoder class found 'scale_info::14'
decoder class found 'Compact<u32>'
decoder class found 'scale_info::15'
decoder class found '(scale_info::16, scale_info::12)'
decoder class found 'scale_info::16'
decoder class found 'scale_info::12'
decoder class found 'Compact<u32>'
Traceback (most recent call last):
<snip>
```

It looks like it's decoding a wrong version of the header because it's expecting much more data than there is available and then fails to decode it while Substrate succeeds in decoding this 174-byte object. Any idea how to make this work?

**Comment by arjanz** [comment]
Are you sure the mentioned data `0xa643a4ac16c...` contains a `Vec`? I debugged the decoding, but I quickly saw the amount of elements will be 724111593 if this was a `Vec`.

Breakpoint: https://github.com/polkascan/py-scale-codec/blob/71de293b557d4935c4a9a8711dfde7203f440c2e/scalecodec/types.py#L957

Also, it seems the decoded metadata is not really being used here?

**Comment by altonen** [comment]
Yes I was mistakenly decoding it as `Vec<BlockAnnounce>`. Decoding it as `BlockAnnounce` also threw an error so I decided to get another block announce for testing. This block announcement:
```rust
BlockAnnounce {
    header: Header {
        parent_hash: 0xa6043a4ac16c3f49d679e82afea2838f8f109c21e674bb8c6ed2b50d128e1b78,
        number: 1,
        state_root: 0xf5180b23a552229670928db4bd7f302bc56bc397ef883530e7e1916df4ef034b,
        extrinsics_root: 0x5758a5d566e73323d51b658539b25a490e56759c84e74b860e91eac0757eb329,
        digest: Digest {
            logs: [
                DigestItem::PreRuntime([97, 117, 114, 97], [43, 130, 176, 16, 0, 0, 0, 0]),
                DigestItem::Seal(
                    [97, 117, 114, 97],
                    [
                        134, 193, 87, 32, 90, 190, 49, 56, 46, 252, 155, 231, 254, 45, 158,
                        133, 58, 178, 200, 166, 95, 170, 17, 148, 0, 117, 171, 208, 6, 168,
                        129, 84, 5, 81, 245, 162, 178, 17, 147, 36, 76, 174, 188, 78, 241, 24,
                        233, 156, 244, 154, 192, 125, 98, 143, 25, 44, 133, 153, 110, 227, 178,
                        91, 119, 133,
                    ],
                ),
            ],
        },
    },
    state: Some(Best),
    data: Some([]),
}
```
is encoded to: `0xa6043a4ac16c3f49d679e82afea2838f8f109c21e674bb8c6ed2b50d128e1b7804f5180b23a552229670928db4bd7f302bc56bc397ef883530e7e1916df4ef034b5758a5d566e73323d51b658539b25a490e56759c84e74b860e91eac0757eb329080661757261202b82b010000000000561757261010186c157205abe31382efc9be7fe2d9e853ab2c8a65faa11940075abd006a881540551f5a2b21193244caebc4ef118e99cf49ac07d628f192c85996ee3b25b77850100`

and this time it's able to decode the header as well when the payload is decoded as `BlockAnnounce`. However, it fails as follows: 
```
<snip>
    raise InvalidScaleTypeValueException("Invalid byte for Compact")
scalecodec.exceptions.InvalidScaleTypeValueException: Invalid byte for Compact
```

but this time it's able to decode all the way to `data`:
```
<snip>
decoder class found 'BlockAnnounce'
decoder class found 'Header'
decoder class found 'Hash'
decoder class found 'Compact<BlockNumber>'
decoder class found 'Hash'
decoder class found 'Hash'
decoder class found 'Digest'
decoder class found 'Vec<DigestItem>'
decoder class found 'Compact<u32>'
decoder class found 'DigestItem'
decoder class found 'PreRuntime'
decoder class found 'ConsensusEngineId'
decoder class found 'HexBytes'
decoder class found 'Compact<u32>'
decoder class found 'RawAuraPreDigest'
decoder class found 'u64'
decoder class found 'DigestItem'
decoder class found 'Seal'
decoder class found 'ConsensusEngineId'
decoder class found 'HexBytes'
decoder class found 'Compact<u32>'
decoder class found 'Option<BlockState>'
decoder class found 'BlockState'
decoder class found 'Option<Vec<u8>>'
decoder class found 'Vec<u8>'
decoder class found 'Compact<u32>'
Traceback (most recent call last):
  File "/home/altonen/.local/lib/python3.10/site-packages/scalecodec/types.py", line 44, in process_compact_bytes
    byte_mod = compact_byte[0] % 4
IndexError: bytearray index out of range

During handling of the above exception, another exception occurred:
<snip>
```
It looks like the length of an empty slice is not decoded correctly as it tries to index into it but it's empty.

> Also, it seems the decoded metadata is not really being used here?

Removed, thanks

**Comment by arjanz** [comment]
I debugged some more and don't know if it was coincidence, but I was able to decode the encoded data when I removed the `Option` from the `state` property:

```
RuntimeConfiguration().update_type_registry({
    "types": {
        "BlockAnnounce": {
            "type": "struct",
            "type_mapping": [
                [
                    "header",
                    "Header",
                ],
                [
                    "state",
                    "BlockState",
                ],
                [
                    "data",
                    "Option<Vec<u8>>",
                ],
            ],
        },
        "BlockState": {
            "type": "enum",
            "type_mapping": [
                [
                    "Normal",
                    "Null",
                ],
                [
                    "Best",
                    "Null",
                ],
            ]
        },
    }
})
```

**Comment by altonen** [comment]
> After removing both `Option` in `state` and `data`, this decodes to:

It's an interesting finding. I guess trictly speaking they could be `None` as specified [here](https://github.com/paritytech/substrate/blob/master/client/network/common/src/sync/message.rs#L190) so I'm not entirely sure what is wrong. But looking at the [code that actually uses it](https://github.com/paritytech/substrate/blob/master/client/network/sync/src/engine.rs#L551-L555), it always sets them as `Some`. There is a comment in the `BlockAnnounce` definition about some `v4 becoming common`, I don't know what that means but what I'm working on is not a very serious project and only used with Substrate so I think just modifying the type definition for Python will hopefully work for all block announces that I need to handle and at least I'm able to decode my small test set of block announcements.

Thanks a lot for figuring this out!
