### ISSUE TITLE
decode block events error after kusama upgraded runtime

### ISSUE THREAD

**Issue by revotu** [polkascan/py-scale-codec#17]
after kusama upgrade runtime yesterday, can't deocde block events  use `scalecodec==0.9.35`

```
from substrateinterface import *

substrate = SubstrateInterface(
    url="wss://kusama-rpc.polkadot.io/",
    address_type=2,
    type_registry_preset='kusama'
)

# block_hash = "0xb8e6b05f3036fa7c9be06d321718380e2642bbbb708d1280c65d2f030c67c125"   # block 2076530
block_hash = "0xef10c239a0c0f71cbfb21d808fc75edc5e550fa6956d847587605cda8c386dcd"   # block 2070349
metadata = substrate.get_block_metadata(block_hash)
block = substrate.get_chain_block(block_hash, metadata_decoder=metadata)
block_events = substrate.get_block_events(block_hash, metadata)
```

error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/substrateinterface/__init__.py", line 402, in get_block_e

  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/base.py", line 255, in decode
    self.value = self.process()
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/block.py", line 291, in process
    element = self.process_type('EventRecord', metadata=self.metadata)
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/base.py", line 329, in process_type
    obj.decode(check_remaining=False)
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/base.py", line 255, in decode
    self.value = self.process()
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/block.py", line 328, in process
    self.event = self.metadata.event_index[self.type][1]
KeyError: '54bf'


```

if use `block_hash = "0xb8e6b05f3036fa7c9be06d321718380e2642bbbb708d1280c65d2f030c67c125"   # block 2076530`

error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/substrateinterface/__init__.py", line 402, in get_block_events
    events_decoder.decode()
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/base.py", line 255, in decode
    self.value = self.process()
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/block.py", line 291, in process
    element = self.process_type('EventRecord', metadata=self.metadata)
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/base.py", line 329, in process_type
    obj.decode(check_remaining=False)
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/base.py", line 255, in decode
    self.value = self.process()
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/block.py", line 332, in process
    arg_type_obj = self.process_type(arg_type)
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/base.py", line 329, in process_type
    obj.decode(check_remaining=False)
  File "/Users/donglongtu/Work/blockchains/polkadot/py-substrate-interface/.env/lib/python3.6/site-packages/scalecodec/base.py", line 262, in decode
    'No more bytes available (offset: {} / length: {})'.format(self.data.offset, self.data.length))
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: No more bytes available (offset: 54 / length: 37)

```

**Comment by arjanz** [comment]
Hi Revotu, 

You have used functions that will be deprecated soon, since last major overhaul there are new functions that also apply SCALE-type versioning. I attached a code snippet for your example:

```
from substrateinterface import SubstrateInterface

substrate = SubstrateInterface(
    url="wss://kusama-rpc.polkadot.io/",
    address_type=2,
    type_registry_preset='kusama'
)

# block_hash = "0xb8e6b05f3036fa7c9be06d321718380e2642bbbb708d1280c65d2f030c67c125"   # block 2076530
block_hash = "0xef10c239a0c0f71cbfb21d808fc75edc5e550fa6956d847587605cda8c386dcd"   # block 2070349
events = substrate.get_runtime_events(block_hash=block_hash)

print(events)

```

I understand it's a bit confusing now, but the old functions are still being used, but we will deprecate them soon. Basically anything starting with `get_runtime_` is part of the new implementation. (like `get_runtime_state` for other storage functions and `get_runtime_block` for fetching a block with its decoded extrinsics. These function are metadata and type registry versioning aware so will always apply the correct metadata and types.

Hope this helps!

**Comment by arjanz** [comment]
Also see https://github.com/polkascan/py-substrate-interface for more info..

**Comment by revotu** [comment]
got it, thanks very much
