### ISSUE TITLE
Exception decoding extrinsics on joystream

### ISSUE THREAD

**Issue by ksinghf** [polkascan/py-scale-codec#3]
I am trying to use the harvester to parse and store data from joystream blockchain. 

Things work fine, but every few blocks I get a exception. I wonder if there is a condition we need to handle decoding extrinsics from joystream similar to this here: https://github.com/polkascan/polkascan-pre-harvester/blob/master/app/processors/converters.py#L645

The block as json is:

`{'block': {'extrinsics': ['0x280302000b7077ca656e01', '0x140308007d1a', '0xd101030a009f0600008c881220713f8a2e4dadbe7420c781b0f58e99d32a70221e7ded05aa3c37feb46f426aa7001100000000000000e229dccd4ad4c4d7c2888a8a419b546c78b8a9d3637597c31435520fe8ac7b2c30429186a9e11bf33e094db68faf347a003f614a7ef9b8e0b955709e2554218b'], 'header': {'digest': {}}}, 'justification': None}`

The metadata is V7 and I have created a gist with the same https://gist.github.com/ksinghf/e8a4fba3f526b2675d2365a897cda592#file-joystream-metadata

The exception I get is:

```
[2019-11-13 18:33:18,819: ERROR/ForkPoolWorker-1] Task app.tasks.accumulate_block_recursive[c0f7cfe5-6441-4744-ba8e-38f8e755739c] raised unexpected: HarvesterCouldNotAddBlock('0x7f89b58497ea3f90709b85a6438cedd20203f3a0da468f521f4da09bec624daa',)
Traceback (most recent call last):
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/harvester/app/tasks.py", line 106, in accumulate_block_recursive
    block = harvester.add_block(block_hash)
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/harvester/app/processors/converters.py", line 651, in add_block
    extrinsic_data = extrinsics_decoder.decode()
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/base.py", line 185, in decode
    self.value = self.process()
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/block.py", line 175, in process
    arg_type_obj = self.process_type(arg.type, metadata=self.metadata)
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/base.py", line 248, in process_type
    obj.decode(check_remaining=False)
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/base.py", line 185, in decode
    self.value = self.process()
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/types.py", line 305, in process
    result[key] = self.process_type(data_type, metadata=self.metadata).value
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/base.py", line 248, in process_type
    obj.decode(check_remaining=False)
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/base.py", line 185, in decode
    self.value = self.process()
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/types.py", line 305, in process
    result[key] = self.process_type(data_type, metadata=self.metadata).value
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/base.py", line 248, in process_type
    obj.decode(check_remaining=False)
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/base.py", line 185, in decode
    self.value = self.process()
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/types.py", line 505, in process
    element_count = self.process_type('Compact<u32>').value
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/base.py", line 248, in process_type
    obj.decode(check_remaining=False)
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/base.py", line 185, in decode
    self.value = self.process()
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/types.py", line 77, in process
    self.process_compact_bytes()
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/scalecodec/types.py", line 33, in process_compact_bytes
    byte_mod = compact_byte[0] % 4
IndexError: bytearray index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/harvester/app/tasks.py", line 66, in __call__
    return super().__call__(*args, **kwargs)
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/nvme/projects/jsgenesis/polkascan/polkascan-pre/harvester/app/tasks.py", line 133, in accumulate_block_recursive
    raise HarvesterCouldNotAddBlock(block_hash) from exc
app.processors.converters.HarvesterCouldNotAddBlock: 0x7f89b58497ea3f90709b85a6438cedd20203f3a0da468f521f4da09bec624daa
```

**Comment by emielvanderhoek** [comment]
I assume this is a node for a new network (not the old Joystream network).
This may be a type-registry issue.

1. You may want to check out your docker-compose file. In the example below on line 21 (and 44) you see a reference to the Joystream type registry. 
https://github.com/polkascan/polkascan-pre/blob/33ee79dea3d7473139c4bdcf4902212f163e091d/docker-compose.joystream.yml#L21
This is however a Substrate 1.0 type registry. You may want to try value `default` or `kusama` since these would more likely reflect substrate 2.0 base types.

2. Additionally you may want to create a new type registry file (e.g. `joystream-new.json`) to define your custom types of your new chain (https://github.com/polkascan/polkascan-pre-harvester/tree/master/app/type_registry).
