### ISSUE TITLE
Bytes offset error

### ISSUE THREAD

**Issue by lana-shanghai** [polkascan/py-scale-codec#42]
Hi Arjan, I came across a new error today and not sure how that happened: 

```
Traceback (most recent call last):
  File "test_node_connection.py", line 70, in <module>
    extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)
  File "/Users/admin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/substrateinterface/base.py", line 1457, in create_signed_extrinsic
    nonce = self.get_account_nonce(keypair.public_key) or 0
  File "/Users/admin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/substrateinterface/base.py", line 1377, in get_account_nonce
    account_info = self.query('System', 'Account', [account_address])
  File "/Users/admin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/substrateinterface/base.py", line 1258, in query
    obj.decode()
  File "/Users/admin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/scalecodec/base.py", line 357, in decode
    raise RemainingScaleBytesNotEmptyException('Current offset: {} / length: {}'.format(self.data.offset, self.data.length))
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Current offset: 69 / length: 80
Admins-MBP:python-cli-substrate admin$ python test_node_connection.py 
Traceback (most recent call last):
  File "test_node_connection.py", line 70, in <module>
    extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)
  File "/Users/admin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/substrateinterface/base.py", line 1457, in create_signed_extrinsic
    nonce = self.get_account_nonce(keypair.public_key) or 0
  File "/Users/admin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/substrateinterface/base.py", line 1377, in get_account_nonce
    account_info = self.query('System', 'Account', [account_address])
  File "/Users/admin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/substrateinterface/base.py", line 1258, in query
    obj.decode()
  File "/Users/admin/.pyenv/versions/3.8.6/lib/python3.8/site-packages/scalecodec/base.py", line 357, in decode
    raise RemainingScaleBytesNotEmptyException('Current offset: {} / length: {}'.format(self.data.offset, self.data.length))
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Current offset: 69 / length: 80
```

the code itself is 

```
substrate = SubstrateInterface(
    url="wss://charlie-node.dev.gridsingularity.com",
    ss58_format=42,
    type_registry_preset='rococo',
    type_registry=custom_type_registry
)

keypair = Keypair.create_from_mnemonic('MNEMONIC')

call = substrate.compose_call(
    call_module='Balances',
    call_function='transfer',
    call_params={
        'dest': '14E5nqKAp3oAJcmzgZhUD2RcptBeUBScxKHgJKU4HPNcKVf3',
        'value': 1000
    }
)

extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)

try:
    receipt = substrate.submit_extrinsic(extrinsic, wait_for_inclusion=True)
    print("Extrinsic '{}' sent and included in block '{}'".format(receipt.extrinsic_hash, receipt.block_hash))

except SubstrateRequestException as e:
    print("Failed to send: {}".format(e))
```

I'm wondering if it could do something with the key encoding? The key format is different apparently for parachains then for the relay chain, if I understand correctly

**Comment by arjanz** [comment]
Because I saw `account_info = self.query('System', 'Account', [account_address])` in the error trace, I think a mismatch in type `AccountInfo` is the culprit.

What you can try is to override `AccountInfo` for: 
```
...
"AccountInfo": "AccountInfoWithDualRefCount",
...
```
or 
```
...
"AccountInfo": "AccountInfoWithTripRefCount",
...
```
or
```
...
"AccountInfo": "AccountInfoWithRefCount",
...
```
Depending on the definition in the node runtime.

What I don't really understand though is why you choose `type_registry_preset='rococo',`, Rococo is a test relay chain, is your node also a relay chain reflecting the types of Rococo? If not  then probably `substrate-node-template` is a better option.
